#!/usr/bin/env node
const Yargs         = require('yargs');
const Usage         = require('../lib/usage');
const Books         = require('../lib/books');
const Versions      = require('../versions');
const { StudyBook } = require('../lib/pdf');

const yargs = Yargs
  .usage( 'Generate a study book for <vers> <book>' )
  .positional( 'vers', {
    describe    : 'The desired version',
    type        : 'string',
    demandOption: true,
  })
  .positional( 'book', {
    describe    : 'The target book',
    type        : 'string',
    demandOption: true,
  })
  .options({
    p: {
      alias   : 'paragraph',
      describe: 'Generate each vers as its own paragraph',
      type    : 'boolean',
      default : false,
    },
    b: {
      alias   : 'base',
      describe: 'The base font size',
      number  : true,
      default : 9,
    },
    s: {
      alias   : 'scale',
      describe: 'Scale all fonts according to the selected base font',
      type    : 'boolean',
      default : false,
    },
    c: {
      alias   : 'cache',
      describe: 'Fetch data from the local cache',
      type    : 'boolean',
      default : false,
    },
  })
  .help();

main().catch(err => { console.error('*** main:', err) });

/****************************************************************************
 * async main
 *
 */
async function main() {
  const args  = yargs.parse();

  //console.log('main() args:', args);
  if (args._.length !== 2) {
    Usage.yargs( yargs );
  }

  const versionName   = args._[0];      // 'NIV84';  //'NIV11';
  const bookName      = args._[1];      // '1 Peter';
  const opts  = {
    linePerVerse: args.paragraph,
    baseFont    : args.base,
    scaleFonts  : args.scale,
    fromCache   : args.cache,
  };

  const study   = new StudyBook( versionName, bookName );
  const outFile = `${study.book.abbr}-${versionName}.pdf`;

  console.log('=== Generate PDF for the %s version of: %s (%s) ...',
              versionName, study.book.name, study.book.abbr);
  const pdf = await study.generate( opts );

  console.log('=== Output to %s ...', outFile);
  pdf.write( outFile );
}
