#!/usr/bin/env node
const Yargs     = require('yargs');
const Versions  = require('../versions');
const Usage     = require('../lib/usage');
const yargs	= Yargs
	.usage('List versions')
  .options({
    l: {
      alias   : 'lang',
      describe: 'The target language',
      default : 'eng',
      type    : 'string',
    },
    t: {
      alias   : 'type',
      describe: 'The target type',
      default : 'all',
      type    : 'string',
    },

    f: {
      alias   : 'force',
      describe: 'Force (re)fetch of the source',
      default : false,
      type    : 'boolean',
    },
    v: {
      alias   : 'verbosity',
      describe: 'Increase debug verbosity',
      count   : true,
    },
    h: { alias : [ '?', 'help' ] },
  })
  .help();

main().catch(err => { console.error('*** main:', err) });

/****************************************************************************
 * async main
 *
 */

async function main() {
  const args      = yargs.parse();
  const versions  = await Versions.list( args );

  versions.forEach( vers => {
    console.log('%s : %s : %s',
                vers.abbreviation.padEnd( 10, ' '),
                vers.local_abbreviation.padEnd( 10, ' '),
                vers.title);
  });
}

// vi: ft=javascript
