#!/usr/bin/env node
const Yargs       = require('yargs');
const Versions    = require('../lib/versions');
const Usage       = require('../lib/usage');
const { inspect } = require('../lib/inspect');

const yargs	= Yargs
	.usage('Find a specific <vers>')
  .positional('vers', {
    describe: 'The desired version',
    type    : 'string',
  })
  .options({
    f: {
      alias   : 'force',
      describe: 'Force (re)fetch',
      default : false,
      type    : 'boolean',
    },
    v: {
      alias   : 'verbosity',
      describe: 'Increase debug verbosity',
      count   : true,
    },
    h: { alias : [ '?', 'help' ] },
  })
  .help();

main().catch(err => { console.error('*** main:', err) });

/****************************************************************************
 * async main
 *
 */
async function main() {
  const args    = yargs.parse();
  const [vers]  = args._;

  if (vers == null) { Usage.yargs( yargs ) }
  args.vers           = vers;
  args.returnVersion  = true;

  const version = await Versions.fetch( args );

  console.log('>>> version[ %s ]:', vers);
  console.log('>>>  id                : %s', version.id);
  console.log('>>>  title             : %s', version.title);
  console.log('>>>  abbreviation      : %s', version.abbreviation);
  console.log('>>>  local_abbreviation: %s', version.local_abbreviation);
}

// vi: ft=javascript
