#!/usr/bin/env node
/**
 *  Ensure the target version has been fetched and extracted and convert the
 *  data to a normalized, database ready JSON format.
 *
 */
const Yargs = require('yargs');
const Yvers = require('../lib/yvers');
const Usage = require('../lib/usage');
const yargs	= Yargs
	.usage('Prepare a <vers> for import into the database')
  .positional('vers', {
    describe: 'The desired version',
    type    : 'string',
  })
  .options({
    f: {
      alias   : 'force',
      describe: 'Force (re)processing',
      default : false,
      type    : 'boolean',
    },
    v: {
      alias   : 'verbosity',
      describe: 'Increase debug verbosity',
      count   : true,
    },
    h: { alias : [ '?', 'help' ] },
  })
  .help();

main().catch(err => { console.error('*** main:', err) });

/****************************************************************************
 * async main
 *
 */
async function main() {
  const args    = yargs.parse();
  const [vers]  = args._;

  if (vers == null) { Usage.yargs( yargs ) }
  args.vers           = vers;
  args.returnVersion  = true;

  const version = await Yvers.prepare.version( args );

  console.log('>>> %s cached to: %s',
              version.abbreviation, version._cache.prepare );
}

// vi: ft=javascript
