#!/usr/bin/env node
/**
 *  Fetch a version and convert all data to JSON format.
 *
 */
const Books = require('../lib/books');
const Yvers = require('../lib/yvers');

async function main() {
  const args  = process.argv.slice(1);
  const vers  = args[1];
  if (vers == null) { _usage( args ) }

  const version = await Yvers.getVersion( vers );
  const path    = await Yvers.toJson( { version } );

  console.log('>>> JSON cached to: %s', path);
}

main().catch(err => { console.error('*** main:', err) });

/****************************************************************************
 * Private helpers {
 *
 */

/**
 *  Present usage information and exit.
 *  @method _usage
 *  @param  args    The incoming arguments {Array};
 *
 *  @return void  (exits the process)
 *  @private
 */
function _usage( args ) {
  const Path  = require('path');
  const prog  = Path.basename( args[0] );
  console.log(`
***
*** Usage: ${prog} version-abbreviation
***
`);

  process.exit(-1);
}

/* Private helpers }
 ****************************************************************************/

// vi: ft=javascript
