verbosity:  1

web_api: #{
  host: localhost #api.ayia.nibious.com
  port: 4000
#} web_api

mongodb: #{   # file:/secrets/mongodb/password
  proto:    mongodb                           # env:MONGODB_PROTO
  host:     localhost                         # env:MONGODB_HOST
  port:     27017                             # env:MONGODB_PORT
  database: ayia                              # env:MONGODB_DATABASE
  user:     ayia                              # env:MONGODB_USER
  password: J5nXwnCQ3wlL4xHjlBqwbwGwIqdRld8W  # env:MONGODB_PASSWORD
#} mongodb
