#!/usr/bin/env node
const Bible = require('../lib');

async function main() {
  const args  = process.argv.slice(1);

  Bible.getVersions()
    .then( versions => {
      versions.response.data.versions.forEach( vers => {
        console.log('%s : %s : %s',
                    vers.abbreviation.padEnd( 10, ' '),
                    vers.local_abbreviation.padEnd( 10, ' '),
                    vers.title);
      });
    })
    .catch(err => {
      console.error('***', err);
    });
}

main();

// vi: ft=javascript
