# ConfigMap {
apiVersion: v1
kind: ConfigMap
metadata: # {
  name:   ayia-admin  #&service_cm_name ayia-admin
  labels:
    app:      ayia-admin
    release:  ayia
# } ConfigMap.metadata
data: # {
  config.yaml: |
    verbosity:  0

    web_admin: # {
      port:   4000
    # } web_admin

    mongodb: # {
      # Using ./etc/mongo-proxy, host == localhost
      proto:    env:MONGO_PROTO
      host:     env:MONGO_HOST
      port:     env:MONGO_PORT
      database: env:MONGO_DATABASE
      user:     env:MONGO_USER
      password: env:MONGO_PASS

      # A map between internal collection names and theh collection within
      # `monbodb.database`.
      collection_map: # {
        versions: versions
        users:    users
      #} mongodb.collection_map
    #} mongodb
# } ConfigMap.data
# } ConfigMap
---
# Service {
apiVersion: v1
kind: Service
metadata: # {
  name: ayia-admin  #&service_name ayia-admin
  labels:
    app:      ayia-admin
    release:  ayia
# } Service.metadata
spec: # {
  selector: # {
    app:      ayia-admin
    release:  ayia
  # } Service.spec.selector
  ports: # {
    - protocol:   TCP
      port:       80    #&service_public_port 80
      targetPort: 4000  #*service_private_port
  # } Service.spec.ports
# } Service.spec
# } Service
---
# VolumeClaim {
{{- $storageClass := .Values.web_admin.persistence.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata: #{
  name: ayia-admin-cache
  labels:
    app:      ayia-admin
    release:  ayia
#} VolumeClaim.metadata
spec: #{
  accessModes:
  {{- range .Values.web_admin.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources: #{
    requests: #{
      storage: {{ .Values.web_admin.persistence.size | quote }}
    # } Deployment.spec.volumeClaimTemplate[0].spec.resources.requests
  # } Deployment.spec.volumeClaimTemplate[0].spec.resources
  {{- if not (eq "-" $storageClass) }}
  {{   printf "storageClassName: %s" $storageClass -}}
  {{  end }}
# } VolumeClaim.spec
# } VolumeClaim
---
# Deployment {
{{- $mongoSecret  := .Values.mongodb.auth.existingSecret -}}
{{- $mongoPort    := .Values.mongodb.containerPorts.mongodb -}}
{{- $mongoSvc     := include "mongodb.fullname" .Subcharts.mongodb }}
apiVersion: apps/v1
kind: Deployment
metadata: # {
  name: ayia-admin
  labels:
    app:      ayia-admin
    release:  ayia
# } Deployment.metadata
spec: # {
  selector:
    matchLabels:
      app:      ayia-admin
      release:  ayia
  strategy:
    type: Recreate
  template: # {
    metadata: # {
      labels: # {
        app:      ayia-admin
        release:  ayia
      # } Deployment.spec.template.metadata.labels
    # } Deployment.spec.template.metadata
    spec: # {
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret }}

      initContainers:
        - name: init
          image: node:21.6.1-alpine3.19
          # Give `node` user (id 1000) permissions a mounted volume
          # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
          command:
            - chown
            - -R
            - node:node
            - /app/cache
          volumeMounts:
            - name:       cache
              mountPath:  /app/cache
          # } Deployment.spec.template.spec.initContainers[init].volumeMounts
        # } Deployment.spec.template.spec.initContainers[server]
      # } Deployment.spec.template.spec.initContainers

      containers: # {
        - name: server # {
          image:  harbor.nibious.com/ayia/web-admin:{{ .Values.web_admin.image.tag }}
          imagePullPolicy: {{ .Values.web_admin.image.pullPolicy |
                                default "IfNotPresent" }}

          env: #{
            - name:   MONGO_PROTO
              value:  mongodb
            - name:   MONGO_HOST
              value:  {{ $mongoSvc }}
            - name:   MONGO_PORT
              value:  {{ $mongoPort | quote }}
            - name:   MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $mongoSecret }}
                  key:  user
            - name:   MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ $mongoSecret }}
                  key:  password
            - name:   MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $mongoSecret }}
                  key:  database
          # } Deployment.spec.template.spec.containers[server].env

          volumeMounts: # {
            - name:       config
              mountPath:  /app/etc/config.yaml
              subPath:    config.yaml
              readOnly:   true
            - name:       cache
              mountPath:  /app/cache
          # } Deployment.spec.template.spec.containers[server].volumeMounts

        # } Deployment.spec.template.spec.containers[server]
      # } Deployment.spec.template.spec.containers

      volumes: # {
        - name: config
          configMap:
            name:   ayia-admin  #*service_cm_name
        - name: cache
          persistentVolumeClaim:
            claimName: ayia-admin-cache
      # } Deployment.spec.template.spec.volumes
    # } Deployment.spec.template.spec
  # } Deployment.spec.template
# } Deployment.spec
# } Deployment
---
# Ingress {
apiVersion: networking.k8s.io/v1
kind:       Ingress
metadata: # {
  name: ayia-admin

  labels: # {
    app:      ayia-admin
    release:  ayia
  # } Ingress.metadata.labels

  annotations: # {
    cert-manager.io/cluster-issuer: "nibious-letsencrypt"
    kubernetes.io.ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  # } Ingress.metadata.annotations

# } Ingress.metadata
spec: # {
  rules:
    - host: admin.ayia.nibious.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ayia-admin  #*service_name
              port:
                number: 80  #*service_public_port
  tls:
    - secretName: admin-ayia-nibious-com-tls
      hosts:
        - admin.ayia.nibious.com
# } Ingress.spec
# } Ingress
---
