# ConfigMap {
apiVersion: v1
kind: ConfigMap
metadata: # {
  name:   ayia-api  #&service_cm_name ayia-api
  labels:
    app:      ayia-api
    release:  ayia
# } ConfigMap.metadata
data: # {
  config.yaml: |
    verbosity:  0

    web_api: # {
      port:   {{ .Values.web_api.port.private }}
    # } web_api

    mongodb: # {
      # Using ./etc/mongo-proxy, host == localhost
      proto:    env:MONGO_PROTO
      host:     env:MONGO_HOST
      port:     env:MONGO_PORT
      database: env:MONGO_DATABASE
      user:     env:MONGO_USER
      password: env:MONGO_PASS

      # A map between internal collection names and theh collection within
      # `monbodb.database`.
      collection_map: # {
        versions: versions
        users:    users
      #} mongodb.collection_map
    #} mongodb
# } ConfigMap.data
# } ConfigMap
---
# Service {
apiVersion: v1
kind: Service
metadata: # {
  name: ayia-api  #&service_name ayia-api
  labels:
    app:      ayia-api
    release:  ayia
# } Service.metadata
spec: # {
  selector: # {
    app:      ayia-api
    release:  ayia
  # } Service.spec.selector
  ports: # {
    - name:       ayia-api
      protocol:   TCP
      port:       {{ .Values.web_api.port.public }}
      targetPort: ayia-api
  # } Service.spec.ports
# } Service.spec
# } Service
---
{{- $mongoSecret := .Values.mongodb.auth.existingSecret -}}
{{- $mongoPort   := .Values.mongodb.containerPorts.mongodb -}}
# Deployment {
apiVersion: apps/v1
kind: Deployment
metadata: # {
  name: ayia-api
  labels:
    app:      ayia-api
    release:  ayia
# } Deployment.metadata
spec: # {
  selector:
    matchLabels:
      app:      ayia-api
      release:  ayia
  strategy:
    type: RollingUpdate   # Recreate
  template: # {
    metadata: # {
      labels: # {
        app:      ayia-api
        release:  ayia
      # } Deployment.spec.template.metadata.labels
    # } Deployment.spec.template.metadata
    spec: # {
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret }}

      securityContext: #{
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: "RuntimeDefault"
      # } securityContext


      containers: # {
        - name: server # {
          image:  registry.nibious.com/ayia/web-api:{{ .Values.web_api.image.tag }}
          imagePullPolicy: {{ .Values.web_api.image.pullPolicy |
                                default "IfNotPresent" }}

          env: #{
            - name:   MONGO_PROTO
              value:  mongodb
            - name:   MONGO_HOST
              value:  mongodb
            - name:   MONGO_PORT
              value:  {{ $mongoPort | quote }}
            - name:   MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $mongoSecret }}
                  key:  user
            - name:   MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ $mongoSecret }}
                  key:  password
            - name:   MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $mongoSecret }}
                  key:  database
          # } Deployment.spec.template.spec.containers[server].env

          volumeMounts: # {
            - name:       config
              mountPath:  /app/etc/config.yaml
              subPath:    config.yaml
              readOnly:   true
          # } Deployment.spec.template.spec.containers[server].volumeMounts

          ports: #{
            - name:           ayia-api
              containerPort:  {{ .Values.web_api.port.private }}
          # } Deployment.spec.template.spec.containers[server].ports

          livenessProbe: # {
            httpGet:
              path: /healthcheck
              port: {{ .Values.web_api.port.private }}
            initialDelaySeconds:  3
            periodSeconds:        3
          # } Deployment.spec.template.spec.containers[server].livenessProbe
          
          securityContext: #{
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          # } securityContext

        # } Deployment.spec.template.spec.containers[server]
      # } Deployment.spec.template.spec.containers

      volumes: # {
        - name: config
          configMap:
            name:   ayia-api  #*service_cm_name
      # } Deployment.spec.template.spec.volumes
    # } Deployment.spec.template.spec
  # } Deployment.spec.template
# } Deployment.spec
# } Deployment
---
# HTTPRoute {
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ayia-api
spec:
  parentRefs:
  - name: contour
    namespace: projectcontour
  hostnames:
  - {{ .Values.web_api.ingress.host }}
  rules:
  - backendRefs:
    - name: ayia-api
      port: {{ .Values.web_api.port.public }}
# } HTTPRoute
---
