---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayia-mongodb
  labels:
    app:      ayia-mongodb
    release:  ayia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayia-mongodb
      release: ayia
  template:
    metadata:
      labels:
        app: ayia-mongodb
        release: ayia
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ayia-mongodb 
      securityContext:
        fsGroup: 1000
      containers:
        - name: mongodb
          image: mongo:{{ .Values.mongodb.image.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
          env:
            - name: MONGO_INITDB_DATABASE
              value:  {{ .Values.mongodb.auth.database }}
            - name: MONGO_INITDB_ROOT_USERNAME
              value:  {{ .Values.mongodb.auth.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.existingSecret }}
                  key: password
          ports:
            - name: db
              containerPort: {{ .Values.mongodb.containerPorts.mongodb }}
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: data
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: ayia-mongodb
    release: ayia
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.containerPorts.mongodb }}
      targetPort: {{ .Values.mongodb.containerPorts.mongodb }}

---

