# ConfigMap {
apiVersion: v1
kind: ConfigMap
metadata: # {
  name:   ayia-ui  #&service_cm_name ayia-ui
  labels:
    app:      ayia-ui
    release:  ayia
# } ConfigMap.metadata
data: # {
  config.yaml: |
    verbosity:  0

    web_ui: # {
      port: {{ .Values.web_ui.port.private }}

      api_map: #{
        versions: https://{{ .Values.web_api.ingress.host }}/api/v2/versions
      #} web_ui.api_map
    # } web_ui
# } ConfigMap.data
# } ConfigMap
---
# Service {
apiVersion: v1
kind: Service
metadata: # {
  name: ayia-ui  #&service_name ayia-ui
  labels:
    app:      ayia-ui
    release:  ayia
# } Service.metadata
spec: # {
  selector: # {
    app:      ayia-ui
    release:  ayia
  # } Service.spec.selector
  ports: # {
    - name:       ayia-ui
      protocol:   TCP
      port:       {{ .Values.web_ui.port.public }}
      targetPort: ayia-ui
  # } Service.spec.ports
# } Service.spec
# } Service
---
# Deployment {
apiVersion: apps/v1
kind: Deployment
metadata: # {
  name: ayia-ui
  labels:
    app:      ayia-ui
    release:  ayia
# } Deployment.metadata
spec: # {
  selector:
    matchLabels:
      app:      ayia-ui
      release:  ayia
  strategy:
    type: RollingUpdate   # Recreate
  template: # {
    metadata: # {
      labels: # {
        app:      ayia-ui
        release:  ayia
      # } Deployment.spec.template.metadata.labels
    # } Deployment.spec.template.metadata
    spec: # {
      imagePullSecrets:
        - name: {{ .Values.global.pullSecret }}

      containers: # {
        - name: server # {
          image:  harbor.nibious.com/ayia/web-ui:{{ .Values.web_ui.image.tag }}
          imagePullPolicy: {{ .Values.web_ui.image.pullPolicy |
                                default "IfNotPresent" }}

          volumeMounts: # {
            - name:       config
              mountPath:  /app/etc/config.yaml
              subPath:    config.yaml
              readOnly:   true
          # } Deployment.spec.template.spec.containers[server].volumeMounts

          ports: #{
            - name:           ayia-ui
              containerPort:  {{ .Values.web_ui.port.private }}
          # } Deployment.spec.template.spec.containers[server].ports

          livenessProbe: # {
            httpGet:
              path: /healthcheck
              port: {{ .Values.web_ui.port.private }}
            initialDelaySeconds:  3
            periodSeconds:        3
          # } Deployment.spec.template.spec.containers[server].livenessProbe

        # } Deployment.spec.template.spec.containers[server]
      # } Deployment.spec.template.spec.containers

      volumes: # {
        - name: config
          configMap:
            name:   ayia-ui  #*service_cm_name
      # } Deployment.spec.template.spec.volumes
    # } Deployment.spec.template.spec
  # } Deployment.spec.template
# } Deployment.spec
# } Deployment
---
# Ingress {
apiVersion: networking.k8s.io/v1
kind:       Ingress
metadata: # {
  name: ayia-ui

  labels: # {
    app:      ayia-ui
    release:  ayia
  # } Ingress.metadata.labels

  annotations: # {
    cert-manager.io/cluster-issuer: "nibious-letsencrypt"
    kubernetes.io.ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  # } Ingress.metadata.annotations

# } Ingress.metadata
spec: # {
  rules:
    - host: {{ .Values.web_ui.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ayia-ui  #*service_name
              port:
                number: {{ .Values.web_ui.port.public }}
  tls:
    - secretName: ui-ayia-tls
      hosts:
        - {{ .Values.web_ui.ingress.host }}
# } Ingress.spec
# } Ingress
---
