global: #{
  # The length of randomly generated secrets
  secretLen:  32

  pullSecret: ayia-pull-creds
#} global

web_admin: #{
  image: #{
    tag:        0.2.7
    #pullPolicy: IfNotPresent
  #} web_admin.image
  persistence: #{
    storageClass: '-'
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  #} web_admin.persistence

  port: #{
    private:  4000
    public:   80
  #} web_admin.port

  ingress: #{
    host: admin.ayia.nibious.com
  #} web_admin.ingress
#} web_admin

web_api: #{
  image: #{
    tag:  0.2.1
    #pullPolicy: IfNotPresent
  #} web_api.image

  port: #{
    private:  4000
    public:   80
  #} web_api.port

  ingress: #{
    host: api.ayia.nibious.com
  #} web_api.ingress
#} web_api

web_ui: #{
  image: #{
    tag:  0.2.16
    #pullPolicy: IfNotPresent
  #} web_ui.image

  port: #{
    private:  5173
    public:   80
  #} web_ui.port

  ingress: #{
    host: ui.ayia.nibious.com
  #} web_ui.ingress
#} web_ui

mongodb: #{
  image: #{
    # :XXX: Use the latest v4 which does NOT require the CPU to support AVX
    tag: 4.2.21-debian-10-r8
  #} mongodb.image

  auth: #{
    username: ayia
    database: ayia

    existingSecret: ayia-mongodb
  #} mongodb.auth
#} mongodb
