global: #{
  # The length of randomly generated secrets
  secretLen:  32

  pullSecret: ayia-pull-creds
#} global

web_admin: #{
  image: #{
    tag:        0.2.10
    #pullPolicy: IfNotPresent
  #} web_admin.image
  persistence: #{
    storageClass: '-'
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  #} web_admin.persistence

  port: #{
    private:  4000
    public:   80
  #} web_admin.port

  ingress: #{
    hosts:
      - admin.ayia.nibious.com
      - admin.ayia.app
  #} web_admin.ingress
#} web_admin

web_api: #{
  image: #{
    tag:  0.2.2
    #pullPolicy: IfNotPresent
  #} web_api.image

  port: #{
    private:  4000
    public:   80
  #} web_api.port

  ingress: #{
    hosts:
      - api.ayia.nibious.com
      - api.ayia.app
  #} web_api.ingress
#} web_api

web_ui: #{
  image: #{
    tag:  0.2.21
    #pullPolicy: IfNotPresent
  #} web_ui.image

  port: #{
    private:  5173
    public:   80
  #} web_ui.port

  ingress: #{
    hosts:
      - ui.ayia.nibious.com
      - ayia.app
  #} web_ui.ingress
#} web_ui

mongodb: #{
  image: #{
    # :XXX: Use the latest v4 which does NOT require the CPU to support AVX
    # Why this tag? ^^^^ that's why
    tag: 4.4.6
  #} mongodb.image

  persistence: #{
    storageClass: '-'
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  #} persistence

  updateStrategy: #{
    type: Recreate
  #} updateStrategy

  containerPorts: #{
    mongodb: 27017
  #} containerPorts

  auth: #{
    username: ayia
    database: ayia

    # If the authentication source differs from the target database
    source:   admin

    existingSecret: ayia-mongodb
  #} mongodb.auth
#} mongodb
