global: #{
  # The length of randomly generated secrets
  secretLen:  32

  pullSecret: ayia-pull-creds
#} global

web_admin: #{
  image: #{
    tag:        0.1.1
    #pullPolicy: IfNotPresent
  #} web_admin.image
  persistence: #{
    storageClass: '-'
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  #} web_admin.persistence
#} web_admin

web_api: #{
  image: #{
    tag:  0.1.0
    #pullPolicy: IfNotPresent
  #} web_api.image
#} web_api

mongodb: #{
  image: #{
    # :XXX: Use the latest v4 which does NOT require the CPU to support AVX
    tag: 4.2.21-debian-10-r8
  #} mongodb.image

  auth: #{
    username: ayia
    database: ayia

    existingSecret: ayia-mongodb
  #} mongodb.auth
#} mongodb
